// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-iQKYfuwhSVonGFQwxbF9ZFxcFRe7FU',
    appId: '1:158246827935:web:739133967c7f5d52f42faa',
    messagingSenderId: '158246827935',
    projectId: 'muscle-app-94fa2',
    authDomain: 'muscle-app-94fa2.firebaseapp.com',
    storageBucket: 'muscle-app-94fa2.firebasestorage.app',
    measurementId: 'G-QF38GGSLFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVjdSyr8TWuSk0WDypu8CDokNMGz8XZ6I',
    appId: '1:158246827935:android:10ca7fca7cb985e9f42faa',
    messagingSenderId: '158246827935',
    projectId: 'muscle-app-94fa2',
    storageBucket: 'muscle-app-94fa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_05Fq60v709JCqlrcZnqc6D9Pz0i8rQ',
    appId: '1:158246827935:ios:4a29cbf5974e5d28f42faa',
    messagingSenderId: '158246827935',
    projectId: 'muscle-app-94fa2',
    storageBucket: 'muscle-app-94fa2.firebasestorage.app',
    iosBundleId: 'com.example.muscleTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV_05Fq60v709JCqlrcZnqc6D9Pz0i8rQ',
    appId: '1:158246827935:ios:4a29cbf5974e5d28f42faa',
    messagingSenderId: '158246827935',
    projectId: 'muscle-app-94fa2',
    storageBucket: 'muscle-app-94fa2.firebasestorage.app',
    iosBundleId: 'com.example.muscleTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ-iQKYfuwhSVonGFQwxbF9ZFxcFRe7FU',
    appId: '1:158246827935:web:5a6b922abcc2a3cbf42faa',
    messagingSenderId: '158246827935',
    projectId: 'muscle-app-94fa2',
    authDomain: 'muscle-app-94fa2.firebaseapp.com',
    storageBucket: 'muscle-app-94fa2.firebasestorage.app',
    measurementId: 'G-MQNZTT8Z44',
  );
}
